In [1]:
import guitarpro
from guitarpro import models
import numpy

ModuleNotFoundError: No module named 'guitarpro'

In [ ]:
# from duration class
#     whole = 1
#     half = 2
#     quarter = 4
#     eighth = 8
#     sixteenth = 16
#     thirtySecond = 32
#     sixtyFourth = 64
#     hundredTwentyEighth = 128
# stored in duration.value

# track.measures - tacts of composition

In [121]:
song = guitarpro.parse('paganini.gp3')

In [195]:
m = t.measures[0]

In [199]:
s = m.timeSignature

In [202]:
s.numerator.

2

In [122]:
tracks = song.tracks

In [123]:
t = tracks[0]

In [124]:
t.measures[0].voices[0].beats[0].duration.value

8

In [133]:
octave, semitone = divmod(64, 12)
print(octave, semitone)

5 4


In [152]:
make_data_matrix(1,2)

['C0',
 'C1',
 'C2',
 'C3',
 'C4',
 'C5',
 'C6',
 'C7',
 'C#0',
 'C#1',
 'C#2',
 'C#3',
 'C#4',
 'C#5',
 'C#6',
 'C#7',
 'D0',
 'D1',
 'D2',
 'D3',
 'D4',
 'D5',
 'D6',
 'D7',
 'D#0',
 'D#1',
 'D#2',
 'D#3',
 'D#4',
 'D#5',
 'D#6',
 'D#7',
 'E0',
 'E1',
 'E2',
 'E3',
 'E4',
 'E5',
 'E6',
 'E7',
 'F0',
 'F1',
 'F2',
 'F3',
 'F4',
 'F5',
 'F6',
 'F7',
 'F#0',
 'F#1',
 'F#2',
 'F#3',
 'F#4',
 'F#5',
 'F#6',
 'F#7',
 'G0',
 'G1',
 'G2',
 'G3',
 'G4',
 'G5',
 'G6',
 'G7',
 'G#0',
 'G#1',
 'G#2',
 'G#3',
 'G#4',
 'G#5',
 'G#6',
 'G#7',
 'A0',
 'A1',
 'A2',
 'A3',
 'A4',
 'A5',
 'A6',
 'A7',
 'A#0',
 'A#1',
 'A#2',
 'A#3',
 'A#4',
 'A#5',
 'A#6',
 'A#7',
 'B0',
 'B1',
 'B2',
 'B3',
 'B4',
 'B5',
 'B6',
 'B7']

In [235]:
data = make_data_matrix(len(t.measures), 1/128)

In [236]:
print(data[0])

['C0', 'C#0', 'D0', 'D#0', 'E0', 'F0', 'F#0', 'G0', 'G#0', 'A0', 'A#0', 'B0', 'C1', 'C#1', 'D1', 'D#1', 'E1', 'F1', 'F#1', 'G1', 'G#1', 'A1', 'A#1', 'B1', 'C2', 'C#2', 'D2', 'D#2', 'E2', 'F2', 'F#2', 'G2', 'G#2', 'A2', 'A#2', 'B2', 'C3', 'C#3', 'D3', 'D#3', 'E3', 'F3', 'F#3', 'G3', 'G#3', 'A3', 'A#3', 'B3', 'C4', 'C#4', 'D4', 'D#4', 'E4', 'F4', 'F#4', 'G4', 'G#4', 'A4', 'A#4', 'B4', 'C5', 'C#5', 'D5', 'D#5', 'E5', 'F5', 'F#5', 'G5', 'G#5', 'A5', 'A#5', 'B5', 'C6', 'C#6', 'D6', 'D#6', 'E6', 'F6', 'F#6', 'G6', 'G#6', 'A6', 'A#6', 'B6', 'C7', 'C#7', 'D7', 'D#7', 'E7', 'F7', 'F#7', 'G7', 'G#7', 'A7', 'A#7', 'B7', 'C8', 'C#8', 'D8', 'D#8', 'E8', 'F8', 'F#8', 'G8', 'G#8', 'A8', 'A#8', 'B8']


In [482]:
def make_data_matrix(measures_amount, base_duration):
    base_labels = 'C C# D D# E F F# G G# A A# B'.split()
    
    # note_label + octave_num
    features = [l + str(i) for i in range(9) for l in base_labels]
    
    data = list()
    data.append(features) # add header
    
    counts_num = int(measures_amount / base_duration)

    empty_object = [[0] * len(features)]
    data += empty_object * counts_num
    data.insert(1, START)
    data.append(END)
    return np.array(data, dtype=object)

In [462]:
def get_note_label(note, strings):
    notes = 'C C# D D# E F F# G G# A A# B'.split()
    
    note_string = strings[note.string - 1].value
    note_semitones = note_string + note.value
    octave, semitone = divmod(note_semitones, len(notes))
    
    return '{note}{octave}'.format(note=notes[semitone], octave=octave)

def get_note_counts(beat, base_duration):
    note_duration = 1 / beat.duration.value
    return int(note_duration / base_duration)

def write_note(note, data, current_point, counts_num):
#     column = data[0].index(note)
#     print(note, column, current_point, counts_num)
#     print(np.where(data[0] == note))
    column = np.where(data[0] == note)[0]
    
    data[current_point:current_point + counts_num,column] = 1

In [453]:
np.where(data[0] == 'D0')

(array([], dtype=int64),)

In [465]:
s[2:6, 3] = 1
s

array([['A', 'B', 'C', 'D'],
       ['0', 'fas', '0', '0'],
       ['0', '0', '0', '1'],
       ['0', '0', '0', '1'],
       ['0', '0', '1', '1'],
       ['0', '0', '0', '1'],
       ['0', '0', '0', '0'],
       ['0', '0', '0', '0'],
       ['0', '0', '0', '0']], 
      dtype='<U3')

In [339]:
s = [['A', 'B', 'C', 'D'], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
print(s)

[['A', 'B', 'C', 'D'], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


In [484]:

START = [1] * 12 * 4 + [0] * 12 * 5
END = [0] * 12 * 4 + [1] * 12 * 5

d = make_data_matrix(108, 1/16)

In [486]:
d[-1]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=object)

In [481]:
data[0]

array(['C0', 'C#0', 'D0', 'D#0', 'E0', 'F0', 'F#0', 'G0', 'G#0', 'A0',
       'A#0', 'B0', 'C1', 'C#1', 'D1', 'D#1', 'E1', 'F1', 'F#1', 'G1',
       'G#1', 'A1', 'A#1', 'B1', 'C2', 'C#2', 'D2', 'D#2', 'E2', 'F2',
       'F#2', 'G2', 'G#2', 'A2', 'A#2', 'B2', 'C3', 'C#3', 'D3', 'D#3',
       'E3', 'F3', 'F#3', 'G3', 'G#3', 'A3', 'A#3', 'B3', 'C4', 'C#4',
       'D4', 'D#4', 'E4', 'F4', 'F#4', 'G4', 'G#4', 'A4', 'A#4', 'B4',
       'C5', 'C#5', 'D5', 'D#5', 'E5', 'F5', 'F#5', 'G5', 'G#5', 'A5',
       'A#5', 'B5', 'C6', 'C#6', 'D6', 'D#6', 'E6', 'F6', 'F#6', 'G6',
       'G#6', 'A6', 'A#6', 'B6', 'C7', 'C#7', 'D7', 'D#7', 'E7', 'F7',
       'F#7', 'G7', 'G#7', 'A7', 'A#7', 'B7', 'C8', 'C#8', 'D8', 'D#8',
       'E8', 'F8', 'F#8', 'G8', 'G#8', 'A8', 'A#8', 'B8'], dtype=object)

In [479]:
def extract_data(track, base_duration):

    strings = track.strings # get strings notes
    base_duration = 1/16

    data = make_data_matrix(len(track.measures), base_duration)
    current_data_point = 1 # current row in data

    for measures in track.measures: # explore tacts
        for voice in measures.voices:
            counts_num = 0
            for beat in voice.beats:
                
                counts_num = get_note_counts(beat, base_duration)

                for note in beat.notes:
                    note_label = get_note_label(note, strings)
                    write_note(note_label, data, current_data_point, counts_num)
                
                current_data_point += counts_num
            
                
    return data

data = extract_data(t, 1/16)

In [424]:
np.where(s == 'fas')

(array([1, 3], dtype=int64), array([1, 3], dtype=int64))

In [471]:
print(data[:50, 50:65])

[['D4' 'D#4' 'E4' 'F4' 'F#4' 'G4' 'G#4' 'A4' 'A#4' 'B4' 'C5' 'C#5' 'D5'
  'D#5' 'E5']
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0

In [404]:
arr = [0] * 20

In [405]:
arr = [arr] * 5

In [407]:
arr[2][4] = 3

In [408]:
print(arr)

[[0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]


In [461]:
# data[1][1] = 5
print(data[:5])


[['C0' 'C#0' 'D0' 'D#0' 'E0' 'F0' 'F#0' 'G0' 'G#0' 'A0' 'A#0' 'B0' 'C1'
  'C#1' 'D1' 'D#1' 'E1' 'F1' 'F#1' 'G1' 'G#1' 'A1' 'A#1' 'B1' 'C2' 'C#2'
  'D2' 'D#2' 'E2' 'F2' 'F#2' 'G2' 'G#2' 'A2' 'A#2' 'B2' 'C3' 'C#3' 'D3'
  'D#3' 'E3' 'F3' 'F#3' 'G3' 'G#3' 'A3' 'A#3' 'B3' 'C4' 'C#4' 'D4' 'D#4'
  'E4' 'F4' 'F#4' 'G4' 'G#4' 'A4' 'A#4' 'B4' 'C5' 'C#5' 'D5' 'D#5' 'E5'
  'F5' 'F#5' 'G5' 'G#5' 'A5' 'A#5' 'B5' 'C6' 'C#6' 'D6' 'D#6' 'E6' 'F6'
  'F#6' 'G6' 'G#6' 'A6' 'A#6' 'B6' 'C7' 'C#7' 'D7' 'D#7' 'E7' 'F7' 'F#7'
  'G7' 'G#7' 'A7' 'A#7' 'B7' 'C8' 'C#8' 'D8' 'D#8' 'E8' 'F8' 'F#8' 'G8'
  'G#8' 'A8' 'A#8' 'B8']
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 'A4' 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 'A4' 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0

In [130]:
t.strings

[GuitarString(number=1, value=64),
 GuitarString(number=2, value=59),
 GuitarString(number=3, value=55),
 GuitarString(number=4, value=50),
 GuitarString(number=5, value=45),
 GuitarString(number=6, value=40)]

In [129]:
for beat in t.measures[1].voices[0].beats:
    print(beat, '\n\n')

Beat(notes=[Note(value=9, velocity=95, string=3, effect=NoteEffect(accentuatedNote=False, bend=None, ghostNote=False, grace=None, hammer=False, harmonic=None, heavyAccentuatedNote=False, leftHandFinger=<Fingering.open: -1>, letRing=False, palmMute=False, rightHandFinger=<Fingering.open: -1>, slides=[], staccato=False, tremoloPicking=None, trill=None, vibrato=False), durationPercent=1.0, swapAccidentals=False, type=<NoteType.normal: 1>)], duration=Duration(value=8, isDotted=False, isDoubleDotted=False, tuplet=Tuplet(enters=1, times=1)), text=None, start=2880, effect=BeatEffect(stroke=BeatStroke(direction=<BeatStrokeDirection.none: 0>, value=0), hasRasgueado=False, pickStroke=<BeatStrokeDirection.none: 0>, chord=None, fadeIn=False, tremoloBar=None, mixTableChange=None, slapEffect=<SlapEffect.none: 0>, vibrato=None), index=None, octave=<Octave.none: 0>, display=BeatDisplay(breakBeam=False, forceBeam=False, beamDirection=<VoiceDirection.none: 0>, tupletBracket=<TupletBracket.none: 0>, brea

In [ ]:
# for all beats
#  find duration
#  find notes

In [81]:
for measure in t.measures:
    for voice in measure.voices:
        for beat in voice.beats:
            for note in beat.notes:
                print(models.PitchClass(note.value), end=' ')
            print(' beat ')

G  beat 
 beat 
G  beat 
G  beat 
A#  beat 
A  beat 
G  beat 
A  beat 
 beat 
G  beat 
G  beat 
B  beat 
A  beat 
G  beat 
G  beat 
 beat 
G  beat 
G  beat 
A#  beat 
A  beat 
G  beat 
A  beat 
G  beat 
 beat 
A#  beat 
 beat 
A#  beat 
A#  beat 
B  beat 
A#  beat 
C  beat 
A#  beat 
 beat 
G  beat 
G  beat 
A#  beat 
A  beat 
G  beat 
G#  beat 
 beat 
G#  beat 
G#  beat 
A#  beat 
G#  beat 
A#  beat 
A  beat 
 beat 
F  beat 
F  beat 
A  beat 
G  beat 
F  beat 
F#  beat 
 beat 
E  beat 
E  beat 
G  beat 
F  beat 
E  beat 
F  beat 
 beat 
D  beat 
D  beat 
F  beat 
E  beat 
D  beat 
D#  beat 
 beat 
E  beat 
D  beat 
F  beat 
D#  beat 
C  beat 
D  beat 
C  beat 
 beat 
C C C  beat 
C#  beat 
D  beat 
D  beat 
D#  beat 
F  beat 
G C C  beat 
A  beat 
A  beat 
A  beat 
B  beat 
C  beat 
C C C  beat 
C#  beat 
D  beat 
D  beat 
D#  beat 
F  beat 
D  beat 
C  beat 
 beat 
F C C  beat 
C  beat 
D  beat 
D  beat 
D  beat 
E  beat 
G C C  beat 
C  beat 
A#  beat 
A#  beat 
A#  beat 
C#  beat 


B  beat 
G  beat 
A#  beat 
G  beat 
G#  beat 
A#  beat 
A#  beat 
F  beat 
F#  beat 
G  beat 
G#  beat 
F  beat 
A#  beat 
G  beat 
G#  beat 
A#  beat 
G  beat 
A  beat 
G#  beat 
A#  beat 
G  beat 
G#  beat 
G#  beat 
G#  beat 
A  beat 
A#  beat 
G  beat 
G#  beat 
G  beat 
F  beat 
E  beat 
F#  beat 
F  beat 
G  beat 
F  beat 
E  beat 
G  beat 
F  beat 
D#  beat 
G  beat 
F  beat 
D#  beat 
G  beat 
F  beat 
G#  beat 
F  beat 
A#  beat 
F#  beat 
F#  beat 
G  beat 
G  beat 
A  beat 
F  beat 
C  beat 
F  beat 
G  beat 
C  beat 
 beat 
A# A A# C  beat 
A  beat 
C#  beat 
C  beat 
A#  beat 
C#  beat 
B  beat 
A  beat 
B  beat 
C#  beat 
A  beat 
A#  beat 
C A# C  beat 
C  beat 
C#  beat 
A#  beat 
B  beat 
C  beat 
C  beat 
D D D# F  beat 
D  beat 
F  beat 
E  beat 
D  beat 
F#  beat 
E  beat 
D  beat 
E  beat 
F#  beat 
D  beat 
G C  beat 
G#  beat 
G G  beat 
A  beat 
A#  beat 
G  beat 
G#  beat 
A  beat 
A#  beat 
A  beat 
G  beat 
A# A B C  beat 
A#  beat 
C  beat 
A  beat 
A#  bea

In [77]:
m.

2880

In [58]:
mrs = tracks[0].measures

In [59]:
m = mrs[0]

In [60]:
voices = m.voices

In [61]:
v = voices[0]

In [62]:
beats = v.beats

In [12]:
note = beats.notes[0]

In [63]:
b = beats[0]

In [64]:
o = b.octave

In [67]:
s = guitarpro.PitchClass()

In [ ]:
s.

In [74]:
for voice in voices:
    for beat in voice.beats:
        for note in beat.notes:
            print(models.PitchClass(note.value))
        print('beat')
    print('voice')

G
beat
beat
G
beat
G
beat
A#
beat
A
beat
G
beat
voice
voice


In [71]:
notes = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 
         'A', 'A#', 'B']

'F#'

In [27]:
p = models.PitchClass(1)

In [28]:
print(p)

C#


In [33]:
for measure in track.measures:
    for voice in measure.voices:
        for beat in note.beats:
            for note in beat.notes:
                noa

In [35]:
s = t1